#!/bin/sh
export WEKA_DIR=$HOME/weka-3-4
export CLUS_DIR=$HOME/files/java/Clus
export CAMANDA_DIR=$HOME/files/java/clusaddon/ClusAmandaRules
java -cp "$CAMANDA_DIR/bin:$CLUS_DIR/bin:$WEKA_DIR/weka.jar:$CLUS_DIR/commons-math-1.0.jar" ClusAmandaRules $*
